# MENuS
## Using Machine Learning to select the best algorithm
* Define the features.
* Include the ingredients generator.
    * Generate an Instance of Ingredients list.
* Finish the model.
* Use minizinc from python.
    * Run it with 3 Algorithms.
    * Add the Instance to the Instances List.
    * Add the time it takes for each Algorithm to the Time Execution Matrix.
    * Transform the Instances List into the Features Array.
    * Travel through the Time Execution Matrix and pick the Algorithms with faster results for each Instance.
    * The Algorithm with the fastest result will be added to the Labels list.

|  | Alg1 | Alg2 | Alg3 |
| --- | --- | --- | --- |
| Ins1 | X | Y | Z |
| Ins2 | X | Y | Z |
| Ins3 | X | Y | Z |
   
* Transform the ingredients list into the dataset for machine learning.
    * Create the Ingredients list.
    * Test with the minizinc model, all the Alg = 3 -> minizinc(300).
    * Take and transform the one that takes less time.
* Training the AI. Split dataset, 70% for training and 30% for prediction, at least 80% accuracy expected. 
----------------------------------------------------------------------------------------------------------

# Generate the Ingredients List

In [31]:
import random
import math

def printN(n):
    n = "n = " + str(n)
    return n

def createProtein():
    quantity = 1#random.randint(1,10)
    protein = random.randint(1, 30)*quantity
    carbohydrate = random.randint(1, 37)*quantity
    fat = random.randint(1, 30)*quantity
    calories = protein*4 + carbohydrate*4 + fat*4
    product = ""
    product = product + str(calories) + "," + str(protein) + "," + str(carbohydrate) + "," + str(fat) + "," + str(random.randint(50, 200)) + "," + str(random.randint(800, 4000)) + "|"
    return product

def createCarbohydrate():
    quantity = 1#random.randint(1,10)
    protein = random.randint(1, 15)*quantity
    carbohydrate = random.randint(1, 75)*quantity
    fat = random.randint(1, 30)*quantity
    calories = protein*4 + carbohydrate*4 + fat*4
    product = ""
    product = product + str(calories) + "," + str(protein) + "," + str(carbohydrate) + "," + str(fat) + "," + str(random.randint(50, 200)) + "," + str(random.randint(800, 4000)) + "|"
    return product

def createFat():
    quantity = 1#random.randint(1,10)
    protein = random.randint(1, 15)*quantity
    carbohydrate = random.randint(1, 37)*quantity
    fat = random.randint(1, 80)*quantity
    calories = protein*4 + carbohydrate*4 +fat*4
    product = ""
    product = product + str(calories) + "," + str(protein) + "," + str(carbohydrate) + "," + str(fat) + "," + str(random.randint(50, 200)) + "," + str(random.randint(800, 4000)) + "|"
    return product

def createGroceries(n):
    longitud = 0
    groceries = "[|"
    for i in range(0,math.floor(n/3)):
        groceries = groceries + createProtein()
        longitud = longitud + 1
    for i in range(0,math.floor(n/3)):
        groceries = groceries + createCarbohydrate()
        longitud = longitud + 1
    for i in range(0,math.floor(n/3)):
        groceries = groceries + createFat()
        longitud = longitud + 1
    for i in range(n-longitud):
        groceries = groceries + createCarbohydrate()
        longitud = longitud + 1
    groceries = groceries + "]"
    return groceries

def printGroceries(n):
    groceries = "groceries = " + str(createGroceries(n))
    return groceries

def createRequirements(d, p):
    #Redondear holgura < 2
    holgura = 1.1
    requirements = "[|" + str(1677*d*p) + "," + str(int(2024*d*p*holgura)) + "|" + str(38*d*p) + "," + str(int(46*d*p*holgura)) + "|" + str(130*d*p) + "," + str(int(130*d*p*holgura)) + "|" + str(57*d*p) + "," + str(int(62*d*p*holgura)) + "|]"
    return requirements

def printRequirements(d, p):
    requirements = "requirements = " + str(createRequirements(d, p)) 
    return requirements

def createDZN(n):
#    days = random.randint(7,15)
#    people = random.randint(1,5)
    days = 3
    people = 1
    dzn = printN(n) + ";\n" + printGroceries(n) + ";\n" + printRequirements(days, people) + ";"
    return(dzn)

#with open('/Users/Sara Maradiago/Desktop/MENUS/data.dzn', 'w') as f:
#    f.write(createDZN(30))

In [100]:
createDZN(10)

'n = 10;\ngroceries = [|204,13,27,11,155,3588|228,11,25,21,182,1175|308,30,27,20,100,1826|348,14,48,25,133,3413|304,12,37,27,98,832|292,10,60,3,102,3322|148,7,11,19,96,1065|312,5,33,40,98,2657|328,7,32,43,146,1482|320,6,47,27,80,1287|];\nrequirements = [|5031,6679|114,151|390,429|171,204|];'

In [94]:
import numpy as np

#-MINIZINC---------------------------------
n_inst=10
ingredient_size=20
il = np.zeros((n_inst), dtype=str)
tem = np.zeros((n_inst, 3))
#------------------------------------------
#-MACHINE LEARNING-------------------------
q_features = 20
features = np.zeros((n_inst, q_features))
labels = np.zeros((n_inst), dtype=int)
#------------------------------------------

# Create Instances List:
def create_IL(n, isz):
    for i in range(0,n):
        il[i] = createDZN(isz)
    print("Updated [il].\n",len(il))
        
# Create Time Execution Matrix:
def create_TEM(n):
    for i in range(n):
        # Here there should be the Minizinc Time results.
        tem[i, :] = np.random.rand(3) * 10
    print("\nUpdated [tem].\n",tem)

In [95]:
create_IL(n_inst,ingredient_size)  
create_TEM(n_inst)

Updated [il].
 10

Updated [tem].
 [[4.15786879 5.54266859 0.37077915]
 [4.17299532 7.69983925 7.17602666]
 [7.49673736 9.89628867 4.70368134]
 [3.04593321 3.51238022 6.3396502 ]
 [8.58984023 8.24438891 1.91599188]
 [5.05881247 6.97948581 2.31519343]
 [9.33324338 5.18899089 6.80676279]
 [5.39629501 1.45046348 9.65005638]
 [7.63194752 8.02929369 2.27023134]
 [3.06627106 5.58905366 3.58032974]]


In [99]:
def create_labels(n,m):
    for i in range(0,n):
        labels[i] = np.argmin(m[i])+1
    print("Updated [labels].\n",labels)
    
create_labels(n_inst, tem)
    

Updated [labels].
 [3 1 3 1 3 3 2 2 3 1]
